from settings import *
font = {
    " ":    pygame.image.load("Font/Font1.png"),
    "0":    pygame.image.load("Font/Font2.png"),
    "1":    pygame.image.load("Font/Font3.png"),
    "2":    pygame.image.load("Font/Font4.png"),
    "3":    pygame.image.load("Font/Font5.png"),
    "4":    pygame.image.load("Font/Font6.png"),
    "5":    pygame.image.load("Font/Font7.png"),
    "6":    pygame.image.load("Font/Font8.png"),
    "7":    pygame.image.load("Font/Font9.png"),
    "8":    pygame.image.load("Font/Font10.png"),
    "9":    pygame.image.load("Font/Font11.png"),
    "A":    pygame.image.load("Font/Font12.png"),
    "B":    pygame.image.load("Font/Font13.png"),
    "C":    pygame.image.load("Font/Font14.png"),
    "D":    pygame.image.load("Font/Font15.png"),
    "E":    pygame.image.load("Font/Font16.png"),
    "F":    pygame.image.load("Font/Font17.png"),
    "G":    pygame.image.load("Font/Font18.png"),
    "H":    pygame.image.load("Font/Font19.png"),
    "I":    pygame.image.load("Font/Font20.png"),
    "J":    pygame.image.load("Font/Font21.png"),
    "K":    pygame.image.load("Font/Font22.png"),
    "L":    pygame.image.load("Font/Font23.png"),
    "M":    pygame.image.load("Font/Font24.png"),
    "N":    pygame.image.load("Font/Font25.png"),
    "O":    pygame.image.load("Font/Font26.png"),
    "P":    pygame.image.load("Font/Font27.png"),
    "Q":    pygame.image.load("Font/Font28.png"),
    "R":    pygame.image.load("Font/Font29.png"),
    "S":    pygame.image.load("Font/Font30.png"),
    "T":    pygame.image.load("Font/Font31.png"),
    "U":    pygame.image.load("Font/Font32.png"),
    "V":    pygame.image.load("Font/Font33.png"),
    "W":    pygame.image.load("Font/Font34.png"),
    "X":    pygame.image.load("Font/Font35.png"),
    "Y":    pygame.image.load("Font/Font36.png"),
    "Z":    pygame.image.load("Font/Font37.png"),
    ":":    pygame.image.load("Font/Font38.png")
}